
package br.com.correios.service;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AtendeClienteService", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", wsdlLocation = "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl")
@org.springframework.stereotype.Service
public class DefaultCorreiosService extends Service
{

    private final static URL ATENDECLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException ATENDECLIENTESERVICE_EXCEPTION;
    private final static QName ATENDECLIENTESERVICE_QNAME = new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATENDECLIENTESERVICE_WSDL_LOCATION = url;
        ATENDECLIENTESERVICE_EXCEPTION = e;
    }

    public DefaultCorreiosService() {
        super(__getWsdlLocation(), ATENDECLIENTESERVICE_QNAME);
    }

    public DefaultCorreiosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATENDECLIENTESERVICE_QNAME, features);
    }

    public DefaultCorreiosService(URL wsdlLocation) {
        super(wsdlLocation, ATENDECLIENTESERVICE_QNAME);
    }

    public DefaultCorreiosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATENDECLIENTESERVICE_QNAME, features);
    }

    public DefaultCorreiosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DefaultCorreiosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaCep
     */
    @WebEndpoint(name = "ConsultaCep")
    public ConsultaCep getPortFromCorreiosWs() {
        return super.getPort(new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClientePort"), ConsultaCep.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AtendeCliente
     */
    @WebEndpoint(name = "ConsultaCep")
    public ConsultaCep getPortFromCorreiosWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClientePort"), ConsultaCep.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATENDECLIENTESERVICE_EXCEPTION!= null) {
            throw ATENDECLIENTESERVICE_EXCEPTION;
        }
        return ATENDECLIENTESERVICE_WSDL_LOCATION;
    }

}
